
export const availableRoomData = [
  {
    title: "Lagos Property Owners",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
  {
    title: "Property Investors",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
  {
    title: "Real Estate Agents Network",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
  {
    title: "Construction & Contractors",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
  {
    title: "Abuja Developers Hub",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
  {
    title: "Property Managers",
    location: "Location",
    heading: "Connect with property owners in Lagos",
    image: "/Images/members-image.svg",
    attendance: "2847 members",
    posts: "156 Post",
    activity: "Last activity : 5 mins ago",
    name: "Join room",
  },
];
