import { TiStarFullOutline } from "react-icons/ti";

export const serviceprofessionalData = [
  {
    image: "/Images/DivineConstrution.svg",
    title: "Divine Construction",
    hours: "4.8 (127)",
    // star: <TiStarFullOutline />,
    subTitle: "Building Contractor",
    location: "Victoria Island, Lagos• 2.5 km",
    name: "Price Range:",
    price: "#15,000-#50,000",
    list: ["Residential", "Commercial", "Renovation"],
    hire: "Hire now",
    chatbox: "/Images/chatbot2.svg",
    telephone: "Images/telephone.svg",
  },
  {
    image: "/Images/DivineConstrution.svg",
    title: "Divine Construction",
    hours: "4.8 (127)",
    // star: <TiStarFullOutline />,
    subTitle: "Building Contractor",
    location: "Victoria Island, Lagos• 2.5 km",
    name: "Price Range:",
    price: "#15,000-#50,000",
    list: ["Residential", "Commercial", "Renovation"],
    hire: "Hire now",
    chatbox: "/Images/chatbot2.svg",
    telephone: "Images/telephone.svg",
  },
  {
    image: "/Images/DivineConstrution.svg",
    title: "Divine Construction",
    hours: "4.8 (127)",
    // star: <TiStarFullOutline />,
    subTitle: "Building Contractor",
    location: "Victoria Island, Lagos• 2.5 km",
    name: "Price Range:",
    price: "#15,000-#50,000",
    list: ["Residential", "Commercial", "Renovation"],
    hire: "Hire now",
    chatbox: "/Images/chatbot2.svg",
    telephone: "Images/telephone.svg",
  },
  {
    image: "/Images/DivineConstrution.svg",
    title: "Divine Construction",
    hours: "4.8 (127)",
    // star: <TiStarFullOutline />,
    subTitle: "Building Contractor",
    location: "Victoria Island, Lagos• 2.5 km",
    name: "Price Range:",
    price: "#15,000-#50,000",
    list: ["Residential", "Commercial", "Renovation"],
    hire: "Hire now",
    chatbox: "/Images/chatbot2.svg",
    telephone: "Images/telephone.svg",
  },
];